# Generated by Django 5.1.2 on 2024-10-16 05:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0003_alter_mavzular_qrlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('tast_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.testlar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
