# Generated by Django 5.1.2 on 2024-10-17 05:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guruhs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('kurs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.kurs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Yonalishs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('fakultet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.fakultets')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='kurs',
            name='yonalish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.yonalishs'),
        ),
    ]
