# Generated by Django 5.1.2 on 2024-10-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakultets',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='guruhs',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='kurs',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='yonalishs',
            options={'ordering': ('-created_at',)},
        ),
    ]
