# Generated by Django 5.2.5 on 2025-08-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='open_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ochiq parol'),
        ),
    ]
