# Generated by Django 5.1.2 on 2024-10-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_fakultets_options_alter_guruhs_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakultets',
            options={},
        ),
        migrations.AlterModelOptions(
            name='guruhs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kurs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='yonalishs',
            options={},
        ),
    ]
