# Generated by Django 5.1.2 on 2024-10-16 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fakultets_guruhs_kurs_yonalishs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guruhs',
            name='kurs_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.kurs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kurs',
            name='yonalish_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.yonalishs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talabas',
            name='fakultet_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.fakultets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talabas',
            name='guruh_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.guruhs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talabas',
            name='kurs_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.kurs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talabas',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='talabas',
            name='yonalish_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.yonalishs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yonalishs',
            name='fakultet_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.fakultets'),
            preserve_default=False,
        ),
    ]
