# Generated by Django 5.1.2 on 2024-10-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_fakultets_options_alter_guruhs_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakultets',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='guruhs',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='kurs',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='yonalishs',
            options={'ordering': ['-fakultet', '-name']},
        ),
        migrations.RenameField(
            model_name='yonalishs',
            old_name='fakultet_id',
            new_name='fakultet',
        ),
        migrations.RemoveField(
            model_name='guruhs',
            name='kurs_id',
        ),
        migrations.RemoveField(
            model_name='kurs',
            name='yonalish_id',
        ),
        migrations.AlterField(
            model_name='fakultets',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Fakultetni kiriting'),
        ),
        migrations.AlterField(
            model_name='guruhs',
            name='name',
            field=models.CharField(choices=[('1-guruh', '1-guruh'), ('2-guruh', '2-guruh'), ('3-guruh', '3-guruh'), ('4-guruh', '4-guruh'), ('5-guruh', '5-guruh'), ('6-guruh', '6-guruh'), ('7-guruh', '7-guruh'), ('8-guruh', '8-guruh'), ('9-guruh', '9-guruh'), ('10-guruh', '10-guruh'), ('11-guruh', '11-guruh'), ('12-guruh', '12-guruh')], default='1-guruh', max_length=255),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='name',
            field=models.CharField(choices=[('1-kurs', '1-kurs'), ('2-kurs', '2-kurs'), ('3-kurs', '3-kurs'), ('4-kurs', '4-kurs')], default='1-kurs', max_length=255),
        ),
        migrations.AlterField(
            model_name='yonalishs',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Yo`nalishni kiriting'),
        ),
    ]
