# Generated by Django 5.1.2 on 2024-10-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_guruhs_kurs_id_kurs_yonalish_id_talabas_fakultet_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fakultets',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='guruhs',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='kurs',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='talabas',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='yonalishs',
            old_name='uid',
            new_name='id',
        ),
    ]
