# Generated by Django 5.1.2 on 2024-10-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_uid_fakultets_id_rename_uid_guruhs_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Talabas',
        ),
    ]
