# Generated by Django 5.1.2 on 2024-10-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_guruhs_name_alter_kurs_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kurs',
            options={'ordering': ['name']},
        ),
    ]
