# Generated by Django 5.1.2 on 2024-10-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_kurs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guruhs',
            options={'ordering': ['name']},
        ),
    ]
