# Generated by Django 5.2.5 on 2025-08-14 15:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mavzus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('mavzu', models.CharField(max_length=255)),
                ('qrcode', models.ImageField(blank=True, upload_to='mavzu')),
                ('qrlink', models.CharField(blank=True, max_length=255)),
                ('yaratish', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['mavzu'],
            },
        ),
        migrations.CreateModel(
            name='Natijas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('talaba', models.CharField(max_length=255)),
                ('togri', models.IntegerField(default=0)),
                ('notogri', models.IntegerField(default=0)),
                ('jami', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['talaba'],
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('savol', models.CharField(max_length=500)),
                ('variant_a', models.CharField(max_length=255)),
                ('variant_b', models.CharField(max_length=255)),
                ('variant_c', models.CharField(max_length=255)),
                ('variant_d', models.CharField(max_length=255)),
                ('togri_javob', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
            options={
                'ordering': ['savol'],
            },
        ),
    ]
