# Generated by Django 4.2.16 on 2024-10-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mavzular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu', models.CharField(max_length=255)),
                ('qrcode', models.ImageField(blank=True, upload_to='mavzu')),
                ('yaratish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Testlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.CharField(max_length=500)),
                ('a', models.CharField(max_length=255)),
                ('b', models.CharField(max_length=255)),
                ('c', models.CharField(max_length=255)),
                ('d', models.CharField(max_length=255)),
                ('togri', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=25)),
                ('mavzu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.mavzular')),
            ],
        ),
    ]
