# Generated by Django 5.2.5 on 2025-08-14 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='natijas',
            name='fakultet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='users.fakultets'),
        ),
        migrations.AddField(
            model_name='natijas',
            name='guruh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='users.guruhs'),
        ),
        migrations.AddField(
            model_name='natijas',
            name='kurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='users.kurs'),
        ),
        migrations.AddField(
            model_name='natijas',
            name='mavzu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='quiz.mavzus'),
        ),
        migrations.AddField(
            model_name='natijas',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='users.yonalishs'),
        ),
        migrations.AddField(
            model_name='tests',
            name='mavzu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='quiz.mavzus'),
        ),
    ]
