# Generated by Django 4.2.16 on 2024-10-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mavzular',
            name='qrlink',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
