# Generated by Django 5.1.1 on 2024-10-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_mavzular_qrlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mavzular',
            name='qrlink',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
