# Generated by Django 5.1.2 on 2024-10-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_natijas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Talabas',
        ),
    ]
