# Generated by Django 5.2.5 on 2025-08-16 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_mavzus_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='natijas',
            name='talaba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to=settings.AUTH_USER_MODEL),
        ),
    ]
