# Generated by Django 5.1.2 on 2024-10-16 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_mavzular_qrlink'),
        ('users', '0005_delete_talabas'),
    ]

    operations = [
        migrations.AddField(
            model_name='mavzular',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mavzular',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mavzular',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Talabas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('fakultet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.fakultets')),
                ('guruh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.guruhs')),
                ('kurs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.kurs')),
                ('tast_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.testlar')),
                ('yonalish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.yonalishs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
