# Generated by Django 5.1.2 on 2024-10-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_delete_talabas'),
    ]

    operations = [
        migrations.AddField(
            model_name='natijas',
            name='jami',
            field=models.IntegerField(default=0),
        ),
    ]
