# Generated by Django 5.1.2 on 2024-10-16 11:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_mavzular_created_at_mavzular_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlar',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testlar',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testlar',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
