# Generated by Django 5.2.5 on 2025-08-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_natijas_talaba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natijas',
            name='talaba',
            field=models.CharField(max_length=255),
        ),
    ]
