# Generated by Django 5.1.2 on 2024-10-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_natijas_jami'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mavzus',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='natijas',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='tests',
            options={'ordering': ('-created_at',)},
        ),
    ]
