# Generated by Django 5.1.2 on 2024-10-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_mavzus_options_alter_natijas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mavzus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tests',
            options={},
        ),
    ]
