# Generated by Django 5.1.2 on 2024-10-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_mavzus_options_alter_tests_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mavzus',
            options={'ordering': ('-mavzu',)},
        ),
        migrations.AlterModelOptions(
            name='natijas',
            options={'ordering': ('-talaba',)},
        ),
        migrations.AlterModelOptions(
            name='tests',
            options={'ordering': ('-savol',)},
        ),
    ]
