# Generated by Django 5.1.1 on 2024-10-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malumot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mavzular',
            name='qrcode',
            field=models.ImageField(null=True, upload_to='mavzu'),
        ),
    ]
