# Generated by Django 5.1.1 on 2024-10-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malumot', '0002_alter_mavzular_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mavzular',
            name='qrcode',
            field=models.ImageField(blank=True, default=1, upload_to='mavzu'),
            preserve_default=False,
        ),
    ]
