# Generated by Django 5.1.1 on 2024-10-05 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malumot', '0003_alter_mavzular_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlar',
            name='mavzu_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='malumot.mavzular'),
            preserve_default=False,
        ),
    ]
