# Generated by Django 5.0.4 on 2024-10-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malumot', '0004_testlar_mavzu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mavzular',
            name='yaratish',
            field=models.BooleanField(default=False),
        ),
    ]
